# Generated by Django 5.0.6 on 2024-06-09 20:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGER', models.CharField(max_length=100)),
                ('prenomGER', models.CharField(max_length=100)),
                ('telGER', models.CharField(max_length=8)),
                ('adresseGER', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAP', models.CharField(max_length=100)),
                ('telAP', models.CharField(max_length=8)),
                ('adresseAP', models.CharField(max_length=50)),
                ('nb_chambres', models.IntegerField()),
                ('nb_salles_bains', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appartements/')),
                ('Gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.gerant')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLOC', models.CharField(max_length=100)),
                ('prenomLOC', models.CharField(max_length=100)),
                ('telLOC', models.CharField(max_length=8)),
                ('adresse', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('date_fin', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('Checkin', 'Enregistré'), ('Pending', 'En attente'), ('Canceled', 'Annulé'), ('Success', 'Réussi')], max_length=20)),
                ('frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.appartement')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.locataire')),
            ],
        ),
    ]
