# Generated by Django 5.0.6 on 2024-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0002_appartement_image1_appartement_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
