# Generated by Django 5.0.6 on 2024-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0003_appartement_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('Paid', 'Payée'), ('Pending', 'En attente'), ('Canceled', 'Annulée'), ('Success', 'Confirmée')], max_length=20),
        ),
    ]
