# Generated by Django 5.0.6 on 2024-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='categorie',
            field=models.CharField(choices=[('jour', 'Jour'), ('mois', 'Mois')], default='jour', max_length=10),
            preserve_default=False,
        ),
    ]
