# Generated by Django 5.0.6 on 2024-06-27 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0006_appartement_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='categorie',
            field=models.CharField(choices=[('jour', 'Par Jour'), ('mois', 'Par Mois')], max_length=10),
        ),
        migrations.CreateModel(
            name='ReservationMoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('jour_payement', models.IntegerField()),
                ('statut', models.CharField(choices=[('Pending', 'En attente'), ('Confirmed', 'Confirmée'), ('Canceled', 'Annulée'), ('Completed', 'Terminée')], default='Pending', max_length=20)),
                ('frais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_payement', models.CharField(choices=[('Cash', 'Cash'), ('Electronic', 'Électronique')], max_length=10)),
                ('signature_locataire', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_gerant', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.appartement')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locapp.locataire')),
            ],
        ),
    ]
