# Generated by Django 5.0.6 on 2024-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0009_remove_paiement_reservation_remove_paiement_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('confirme', 'Confirmé'), ('refuse', 'Refusé')], default='en_cours', max_length=10),
        ),
    ]
