# Generated by Django 5.0.6 on 2024-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locapp', '0010_paiement_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
